language: python
# python versions to use during the tests
python:
    - "3.6"
install:
    - pip install coveralls
    - pip install -r requirements.txt
script:
    - coverage run -m unittest discover -p 'test*.py'
branches:
  only:
   - master
after_success:
    - coveralls